/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'alertType' : string,
  'active' : boolean,
  'threshold' : Float,
  'note' : string,
}
export interface AlertTrigger {
  'alertId' : bigint,
  'message' : string,
  'timestamp' : bigint,
}
export interface DataFreshnessRecord {
  'isStale' : boolean,
  'lastUpdated' : bigint,
  'latencyMs' : bigint,
  'metricName' : string,
  'exchange' : string,
}
export interface EventReplay {
  'flows' : Array<ExchangeFlow>,
  'priceHistory' : Array<MarketSnapshot>,
  'liquidations' : Array<LiquidationEvent>,
  'event' : [] | [ImpulseEvent],
}
export interface ExchangeFlow {
  'inflowBTC' : Float,
  'timestamp' : bigint,
  'outflowBTC' : Float,
  'exchange' : string,
}
export type Float = number;
export interface ImpulseEvent {
  'id' : bigint,
  'description' : string,
  'timestamp' : bigint,
  'exchanges' : Array<string>,
  'magnitude' : Float,
  'eventType' : string,
}
export interface LiquidationEvent {
  'side' : string,
  'timestamp' : bigint,
  'amountUSD' : Float,
  'exchange' : string,
}
export interface LiquidationWindow {
  'totalVolume' : Float,
  'window' : string,
  'longLiquidations' : Float,
  'shortLiquidations' : Float,
  'isCluster' : boolean,
}
export interface LiquidityScore {
  'oiScore' : bigint,
  'score' : bigint,
  'impulseScore' : bigint,
  'orderBookScore' : bigint,
  'fundingScore' : bigint,
}
export interface MarketSnapshot {
  'openInterest' : Float,
  'timestamp' : bigint,
  'fundingRate' : Float,
  'exchange' : string,
  'price' : Float,
}
export interface NetflowPoint {
  'isSpike' : boolean,
  'netflow' : Float,
  'inflow' : Float,
  'timestamp' : bigint,
  'exchange' : string,
  'outflow' : Float,
}
export interface OrderBookDepth {
  'bidDepth1' : Float,
  'askDepth1' : Float,
  'timestamp' : bigint,
  'bidDepth01' : Float,
  'bidDepth05' : Float,
  'askDepth01' : Float,
  'askDepth05' : Float,
  'exchange' : string,
}
export interface SpreadSnapshot {
  'isAbnormal' : boolean,
  'lowestExchange' : string,
  'highestExchange' : string,
  'highestPrice' : Float,
  'timestamp' : bigint,
  'lowestPrice' : Float,
  'spreadPct' : Float,
}
export interface SynchronizedImpulseEvent {
  'id' : bigint,
  'volumeSpikeFactor' : Float,
  'direction' : string,
  'description' : string,
  'timestamp' : bigint,
  'priceChangePct' : Float,
  'exchanges' : Array<string>,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface VolumeMetric {
  'volume1min' : Float,
  'isSpike' : boolean,
  'timestamp' : bigint,
  'exchange' : string,
  'relativeVolume' : Float,
  'volume60minAvg' : Float,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addAlert' : ActorMethod<[string, Float, string], bigint>,
  'deleteAlert' : ActorMethod<[bigint], boolean>,
  'fetchDataCycle' : ActorMethod<[], undefined>,
  'getAlertTriggers' : ActorMethod<[bigint], Array<AlertTrigger>>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getBinanceBTCPrice' : ActorMethod<[], string>,
  'getDataFreshness' : ActorMethod<[], Array<DataFreshnessRecord>>,
  'getEventReplay' : ActorMethod<[bigint], EventReplay>,
  'getExchangeFlows' : ActorMethod<[bigint], Array<ExchangeFlow>>,
  'getFundingRates' : ActorMethod<[], Array<[string, Float]>>,
  'getImpulseEvents' : ActorMethod<[bigint], Array<ImpulseEvent>>,
  'getLatestPrices' : ActorMethod<[], Array<[string, Float]>>,
  'getLiquidationWindows' : ActorMethod<[], Array<LiquidationWindow>>,
  'getLiquidations' : ActorMethod<[bigint], Array<LiquidationEvent>>,
  'getLiquidityScore' : ActorMethod<[], LiquidityScore>,
  'getNetflowHistory' : ActorMethod<[string, string], Array<NetflowPoint>>,
  'getOpenInterest' : ActorMethod<[], Array<[string, Float]>>,
  'getOrderBookDepth' : ActorMethod<[], Array<[string, OrderBookDepth]>>,
  'getPriceHistory' : ActorMethod<[string, bigint], Array<MarketSnapshot>>,
  'getSpreadSnapshot' : ActorMethod<[], [] | [SpreadSnapshot]>,
  'getSynchronizedImpulseEvents' : ActorMethod<
    [bigint],
    Array<SynchronizedImpulseEvent>
  >,
  'getVolumeMetrics' : ActorMethod<[], Array<VolumeMetric>>,
  'init' : ActorMethod<[], undefined>,
  'isLiveData' : ActorMethod<[], boolean>,
  'startDataFetching' : ActorMethod<[], undefined>,
  'transformHttpResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'triggerManualRefresh' : ActorMethod<[], string>,
  'updateAlert' : ActorMethod<[bigint, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];