/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Float = IDL.Float64;
export const AlertTrigger = IDL.Record({
  'alertId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'alertType' : IDL.Text,
  'active' : IDL.Bool,
  'threshold' : Float,
  'note' : IDL.Text,
});
export const DataFreshnessRecord = IDL.Record({
  'isStale' : IDL.Bool,
  'lastUpdated' : IDL.Int,
  'latencyMs' : IDL.Int,
  'metricName' : IDL.Text,
  'exchange' : IDL.Text,
});
export const ExchangeFlow = IDL.Record({
  'inflowBTC' : Float,
  'timestamp' : IDL.Int,
  'outflowBTC' : Float,
  'exchange' : IDL.Text,
});
export const MarketSnapshot = IDL.Record({
  'openInterest' : Float,
  'timestamp' : IDL.Int,
  'fundingRate' : Float,
  'exchange' : IDL.Text,
  'price' : Float,
});
export const LiquidationEvent = IDL.Record({
  'side' : IDL.Text,
  'timestamp' : IDL.Int,
  'amountUSD' : Float,
  'exchange' : IDL.Text,
});
export const ImpulseEvent = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'exchanges' : IDL.Vec(IDL.Text),
  'magnitude' : Float,
  'eventType' : IDL.Text,
});
export const EventReplay = IDL.Record({
  'flows' : IDL.Vec(ExchangeFlow),
  'priceHistory' : IDL.Vec(MarketSnapshot),
  'liquidations' : IDL.Vec(LiquidationEvent),
  'event' : IDL.Opt(ImpulseEvent),
});
export const LiquidationWindow = IDL.Record({
  'totalVolume' : Float,
  'window' : IDL.Text,
  'longLiquidations' : Float,
  'shortLiquidations' : Float,
  'isCluster' : IDL.Bool,
});
export const LiquidityScore = IDL.Record({
  'oiScore' : IDL.Nat,
  'score' : IDL.Nat,
  'impulseScore' : IDL.Nat,
  'orderBookScore' : IDL.Nat,
  'fundingScore' : IDL.Nat,
});
export const NetflowPoint = IDL.Record({
  'isSpike' : IDL.Bool,
  'netflow' : Float,
  'inflow' : Float,
  'timestamp' : IDL.Int,
  'exchange' : IDL.Text,
  'outflow' : Float,
});
export const OrderBookDepth = IDL.Record({
  'bidDepth1' : Float,
  'askDepth1' : Float,
  'timestamp' : IDL.Int,
  'bidDepth01' : Float,
  'bidDepth05' : Float,
  'askDepth01' : Float,
  'askDepth05' : Float,
  'exchange' : IDL.Text,
});
export const SpreadSnapshot = IDL.Record({
  'isAbnormal' : IDL.Bool,
  'lowestExchange' : IDL.Text,
  'highestExchange' : IDL.Text,
  'highestPrice' : Float,
  'timestamp' : IDL.Int,
  'lowestPrice' : Float,
  'spreadPct' : Float,
});
export const SynchronizedImpulseEvent = IDL.Record({
  'id' : IDL.Nat,
  'volumeSpikeFactor' : Float,
  'direction' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'priceChangePct' : Float,
  'exchanges' : IDL.Vec(IDL.Text),
});
export const VolumeMetric = IDL.Record({
  'volume1min' : Float,
  'isSpike' : IDL.Bool,
  'timestamp' : IDL.Int,
  'exchange' : IDL.Text,
  'relativeVolume' : Float,
  'volume60minAvg' : Float,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addAlert' : IDL.Func([IDL.Text, Float, IDL.Text], [IDL.Nat], []),
  'auth' : IDL.Func([IDL.Vec(IDL.Nat8)], [], ['query']),
  'deleteAlert' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'fetchDataCycle' : IDL.Func([], [], []),
  'getAlertTriggers' : IDL.Func([IDL.Nat], [IDL.Vec(AlertTrigger)], ['query']),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getBinanceBTCPrice' : IDL.Func([], [IDL.Text], []),
  'getDataFreshness' : IDL.Func([], [IDL.Vec(DataFreshnessRecord)], ['query']),
  'getEventReplay' : IDL.Func([IDL.Nat], [EventReplay], ['query']),
  'getExchangeFlows' : IDL.Func([IDL.Nat], [IDL.Vec(ExchangeFlow)], ['query']),
  'getFundingRates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Float))],
      ['query'],
    ),
  'getImpulseEvents' : IDL.Func([IDL.Nat], [IDL.Vec(ImpulseEvent)], ['query']),
  'getLatestPrices' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Float))],
      ['query'],
    ),
  'getLiquidationWindows' : IDL.Func(
      [],
      [IDL.Vec(LiquidationWindow)],
      ['query'],
    ),
  'getLiquidations' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LiquidationEvent)],
      ['query'],
    ),
  'getLiquidityScore' : IDL.Func([], [LiquidityScore], ['query']),
  'getNetflowHistory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(NetflowPoint)],
      ['query'],
    ),
  'getOpenInterest' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Float))],
      ['query'],
    ),
  'getOrderBookDepth' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, OrderBookDepth))],
      ['query'],
    ),
  'getPriceHistory' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(MarketSnapshot)],
      ['query'],
    ),
  'getSpreadSnapshot' : IDL.Func([], [IDL.Opt(SpreadSnapshot)], ['query']),
  'getSynchronizedImpulseEvents' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SynchronizedImpulseEvent)],
      ['query'],
    ),
  'getVolumeMetrics' : IDL.Func([], [IDL.Vec(VolumeMetric)], ['query']),
  'init' : IDL.Func([], [], []),
  'startDataFetching' : IDL.Func([], [], []),
  'transformHttpResponse' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerManualRefresh' : IDL.Func([], [IDL.Text], []),
  'updateAlert' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Float = IDL.Float64;
  const AlertTrigger = IDL.Record({
    'alertId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'alertType' : IDL.Text,
    'active' : IDL.Bool,
    'threshold' : Float,
    'note' : IDL.Text,
  });
  const DataFreshnessRecord = IDL.Record({
    'isStale' : IDL.Bool,
    'lastUpdated' : IDL.Int,
    'latencyMs' : IDL.Int,
    'metricName' : IDL.Text,
    'exchange' : IDL.Text,
  });
  const ExchangeFlow = IDL.Record({
    'inflowBTC' : Float,
    'timestamp' : IDL.Int,
    'outflowBTC' : Float,
    'exchange' : IDL.Text,
  });
  const MarketSnapshot = IDL.Record({
    'openInterest' : Float,
    'timestamp' : IDL.Int,
    'fundingRate' : Float,
    'exchange' : IDL.Text,
    'price' : Float,
  });
  const LiquidationEvent = IDL.Record({
    'side' : IDL.Text,
    'timestamp' : IDL.Int,
    'amountUSD' : Float,
    'exchange' : IDL.Text,
  });
  const ImpulseEvent = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'exchanges' : IDL.Vec(IDL.Text),
    'magnitude' : Float,
    'eventType' : IDL.Text,
  });
  const EventReplay = IDL.Record({
    'flows' : IDL.Vec(ExchangeFlow),
    'priceHistory' : IDL.Vec(MarketSnapshot),
    'liquidations' : IDL.Vec(LiquidationEvent),
    'event' : IDL.Opt(ImpulseEvent),
  });
  const LiquidationWindow = IDL.Record({
    'totalVolume' : Float,
    'window' : IDL.Text,
    'longLiquidations' : Float,
    'shortLiquidations' : Float,
    'isCluster' : IDL.Bool,
  });
  const LiquidityScore = IDL.Record({
    'oiScore' : IDL.Nat,
    'score' : IDL.Nat,
    'impulseScore' : IDL.Nat,
    'orderBookScore' : IDL.Nat,
    'fundingScore' : IDL.Nat,
  });
  const NetflowPoint = IDL.Record({
    'isSpike' : IDL.Bool,
    'netflow' : Float,
    'inflow' : Float,
    'timestamp' : IDL.Int,
    'exchange' : IDL.Text,
    'outflow' : Float,
  });
  const OrderBookDepth = IDL.Record({
    'bidDepth1' : Float,
    'askDepth1' : Float,
    'timestamp' : IDL.Int,
    'bidDepth01' : Float,
    'bidDepth05' : Float,
    'askDepth01' : Float,
    'askDepth05' : Float,
    'exchange' : IDL.Text,
  });
  const SpreadSnapshot = IDL.Record({
    'isAbnormal' : IDL.Bool,
    'lowestExchange' : IDL.Text,
    'highestExchange' : IDL.Text,
    'highestPrice' : Float,
    'timestamp' : IDL.Int,
    'lowestPrice' : Float,
    'spreadPct' : Float,
  });
  const SynchronizedImpulseEvent = IDL.Record({
    'id' : IDL.Nat,
    'volumeSpikeFactor' : Float,
    'direction' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'priceChangePct' : Float,
    'exchanges' : IDL.Vec(IDL.Text),
  });
  const VolumeMetric = IDL.Record({
    'volume1min' : Float,
    'isSpike' : IDL.Bool,
    'timestamp' : IDL.Int,
    'exchange' : IDL.Text,
    'relativeVolume' : Float,
    'volume60minAvg' : Float,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addAlert' : IDL.Func([IDL.Text, Float, IDL.Text], [IDL.Nat], []),
    'auth' : IDL.Func([IDL.Vec(IDL.Nat8)], [], ['query']),
    'deleteAlert' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'fetchDataCycle' : IDL.Func([], [], []),
    'getAlertTriggers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AlertTrigger)],
        ['query'],
      ),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getBinanceBTCPrice' : IDL.Func([], [IDL.Text], []),
    'getDataFreshness' : IDL.Func(
        [],
        [IDL.Vec(DataFreshnessRecord)],
        ['query'],
      ),
    'getEventReplay' : IDL.Func([IDL.Nat], [EventReplay], ['query']),
    'getExchangeFlows' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ExchangeFlow)],
        ['query'],
      ),
    'getFundingRates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Float))],
        ['query'],
      ),
    'getImpulseEvents' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ImpulseEvent)],
        ['query'],
      ),
    'getLatestPrices' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Float))],
        ['query'],
      ),
    'getLiquidationWindows' : IDL.Func(
        [],
        [IDL.Vec(LiquidationWindow)],
        ['query'],
      ),
    'getLiquidations' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LiquidationEvent)],
        ['query'],
      ),
    'getLiquidityScore' : IDL.Func([], [LiquidityScore], ['query']),
    'getNetflowHistory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(NetflowPoint)],
        ['query'],
      ),
    'getOpenInterest' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Float))],
        ['query'],
      ),
    'getOrderBookDepth' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, OrderBookDepth))],
        ['query'],
      ),
    'getPriceHistory' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(MarketSnapshot)],
        ['query'],
      ),
    'getSpreadSnapshot' : IDL.Func([], [IDL.Opt(SpreadSnapshot)], ['query']),
    'getSynchronizedImpulseEvents' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SynchronizedImpulseEvent)],
        ['query'],
      ),
    'getVolumeMetrics' : IDL.Func([], [IDL.Vec(VolumeMetric)], ['query']),
    'init' : IDL.Func([], [], []),
    'startDataFetching' : IDL.Func([], [], []),
    'transformHttpResponse' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerManualRefresh' : IDL.Func([], [IDL.Text], []),
    'updateAlert' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };