/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface LiquidationEvent {
    side: string;
    timestamp: bigint;
    amountUSD: Float;
    exchange: string;
}
export interface EventReplay {
    flows: Array<ExchangeFlow>;
    priceHistory: Array<MarketSnapshot>;
    liquidations: Array<LiquidationEvent>;
    event?: ImpulseEvent;
}
export interface LiquidityScore {
    oiScore: bigint;
    score: bigint;
    impulseScore: bigint;
    orderBookScore: bigint;
    fundingScore: bigint;
}
export interface ExchangeFlow {
    inflowBTC: Float;
    timestamp: bigint;
    outflowBTC: Float;
    exchange: string;
}
export interface DataFreshnessRecord {
    isStale: boolean;
    lastUpdated: bigint;
    latencyMs: bigint;
    metricName: string;
    exchange: string;
}
export interface AlertTrigger {
    alertId: bigint;
    message: string;
    timestamp: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface VolumeMetric {
    volume1min: Float;
    isSpike: boolean;
    timestamp: bigint;
    exchange: string;
    relativeVolume: Float;
    volume60minAvg: Float;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SynchronizedImpulseEvent {
    id: bigint;
    volumeSpikeFactor: Float;
    direction: string;
    description: string;
    timestamp: bigint;
    priceChangePct: Float;
    exchanges: Array<string>;
}
export interface SpreadSnapshot {
    isAbnormal: boolean;
    lowestExchange: string;
    highestExchange: string;
    highestPrice: Float;
    timestamp: bigint;
    lowestPrice: Float;
    spreadPct: Float;
}
export interface LiquidationWindow {
    totalVolume: Float;
    window: string;
    longLiquidations: Float;
    shortLiquidations: Float;
    isCluster: boolean;
}
export interface MarketSnapshot {
    openInterest: Float;
    timestamp: bigint;
    fundingRate: Float;
    exchange: string;
    price: Float;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface OrderBookDepth {
    bidDepth1: Float;
    askDepth1: Float;
    timestamp: bigint;
    bidDepth01: Float;
    bidDepth05: Float;
    askDepth01: Float;
    askDepth05: Float;
    exchange: string;
}
export type Float = number;
export interface NetflowPoint {
    isSpike: boolean;
    netflow: Float;
    inflow: Float;
    timestamp: bigint;
    exchange: string;
    outflow: Float;
}
export interface Alert {
    id: bigint;
    alertType: string;
    active: boolean;
    threshold: Float;
    note: string;
}
export interface ImpulseEvent {
    id: bigint;
    description: string;
    timestamp: bigint;
    exchanges: Array<string>;
    magnitude: Float;
    eventType: string;
}
export interface backendInterface {
    addAlert(alertType: string, threshold: Float, note: string): Promise<bigint>;
    auth(caller: Uint8Array): Promise<void>;
    deleteAlert(id: bigint): Promise<boolean>;
    fetchDataCycle(): Promise<void>;
    getAlertTriggers(limit: bigint): Promise<Array<AlertTrigger>>;
    getAlerts(): Promise<Array<Alert>>;
    getBinanceBTCPrice(): Promise<string>;
    getDataFreshness(): Promise<Array<DataFreshnessRecord>>;
    getEventReplay(impulseEventId: bigint): Promise<EventReplay>;
    getExchangeFlows(limit: bigint): Promise<Array<ExchangeFlow>>;
    getFundingRates(): Promise<Array<[string, Float]>>;
    getImpulseEvents(limit: bigint): Promise<Array<ImpulseEvent>>;
    getLatestPrices(): Promise<Array<[string, Float]>>;
    getLiquidationWindows(): Promise<Array<LiquidationWindow>>;
    getLiquidations(limit: bigint): Promise<Array<LiquidationEvent>>;
    getLiquidityScore(): Promise<LiquidityScore>;
    getNetflowHistory(exchange: string, window: string): Promise<Array<NetflowPoint>>;
    getOpenInterest(): Promise<Array<[string, Float]>>;
    getOrderBookDepth(): Promise<Array<[string, OrderBookDepth]>>;
    getPriceHistory(exchange: string, limit: bigint): Promise<Array<MarketSnapshot>>;
    getSpreadSnapshot(): Promise<SpreadSnapshot | null>;
    getSynchronizedImpulseEvents(limit: bigint): Promise<Array<SynchronizedImpulseEvent>>;
    getVolumeMetrics(): Promise<Array<VolumeMetric>>;
    init(): Promise<void>;
    startDataFetching(): Promise<void>;
    transformHttpResponse(input: TransformationInput): Promise<TransformationOutput>;
    triggerManualRefresh(): Promise<string>;
    updateAlert(id: bigint, active: boolean): Promise<boolean>;
}
import type { EventReplay as _EventReplay, ExchangeFlow as _ExchangeFlow, ImpulseEvent as _ImpulseEvent, LiquidationEvent as _LiquidationEvent, MarketSnapshot as _MarketSnapshot, SpreadSnapshot as _SpreadSnapshot } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAlert(arg0: string, arg1: Float, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlert(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlert(arg0, arg1, arg2);
            return result;
        }
    }
    async auth(arg0: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.auth(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.auth(arg0);
            return result;
        }
    }
    async deleteAlert(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlert(arg0);
            return result;
        }
    }
    async fetchDataCycle(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchDataCycle();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchDataCycle();
            return result;
        }
    }
    async getAlertTriggers(arg0: bigint): Promise<Array<AlertTrigger>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertTriggers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertTriggers(arg0);
            return result;
        }
    }
    async getAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts();
            return result;
        }
    }
    async getBinanceBTCPrice(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBinanceBTCPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBinanceBTCPrice();
            return result;
        }
    }
    async getDataFreshness(): Promise<Array<DataFreshnessRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataFreshness();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataFreshness();
            return result;
        }
    }
    async getEventReplay(arg0: bigint): Promise<EventReplay> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventReplay(arg0);
                return from_candid_EventReplay_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventReplay(arg0);
            return from_candid_EventReplay_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExchangeFlows(arg0: bigint): Promise<Array<ExchangeFlow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExchangeFlows(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExchangeFlows(arg0);
            return result;
        }
    }
    async getFundingRates(): Promise<Array<[string, Float]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFundingRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFundingRates();
            return result;
        }
    }
    async getImpulseEvents(arg0: bigint): Promise<Array<ImpulseEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImpulseEvents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImpulseEvents(arg0);
            return result;
        }
    }
    async getLatestPrices(): Promise<Array<[string, Float]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestPrices();
            return result;
        }
    }
    async getLiquidationWindows(): Promise<Array<LiquidationWindow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiquidationWindows();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiquidationWindows();
            return result;
        }
    }
    async getLiquidations(arg0: bigint): Promise<Array<LiquidationEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiquidations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiquidations(arg0);
            return result;
        }
    }
    async getLiquidityScore(): Promise<LiquidityScore> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiquidityScore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiquidityScore();
            return result;
        }
    }
    async getNetflowHistory(arg0: string, arg1: string): Promise<Array<NetflowPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNetflowHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNetflowHistory(arg0, arg1);
            return result;
        }
    }
    async getOpenInterest(): Promise<Array<[string, Float]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenInterest();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenInterest();
            return result;
        }
    }
    async getOrderBookDepth(): Promise<Array<[string, OrderBookDepth]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderBookDepth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderBookDepth();
            return result;
        }
    }
    async getPriceHistory(arg0: string, arg1: bigint): Promise<Array<MarketSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriceHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriceHistory(arg0, arg1);
            return result;
        }
    }
    async getSpreadSnapshot(): Promise<SpreadSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpreadSnapshot();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpreadSnapshot();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSynchronizedImpulseEvents(arg0: bigint): Promise<Array<SynchronizedImpulseEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSynchronizedImpulseEvents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSynchronizedImpulseEvents(arg0);
            return result;
        }
    }
    async getVolumeMetrics(): Promise<Array<VolumeMetric>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolumeMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolumeMetrics();
            return result;
        }
    }
    async init(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.init();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.init();
            return result;
        }
    }
    async startDataFetching(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startDataFetching();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startDataFetching();
            return result;
        }
    }
    async transformHttpResponse(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformHttpResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformHttpResponse(arg0);
            return result;
        }
    }
    async triggerManualRefresh(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerManualRefresh();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerManualRefresh();
            return result;
        }
    }
    async updateAlert(arg0: bigint, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAlert(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAlert(arg0, arg1);
            return result;
        }
    }
}
function from_candid_EventReplay_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventReplay): EventReplay {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ImpulseEvent]): ImpulseEvent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SpreadSnapshot]): SpreadSnapshot | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flows: Array<_ExchangeFlow>;
    priceHistory: Array<_MarketSnapshot>;
    liquidations: Array<_LiquidationEvent>;
    event: [] | [_ImpulseEvent];
}): {
    flows: Array<ExchangeFlow>;
    priceHistory: Array<MarketSnapshot>;
    liquidations: Array<LiquidationEvent>;
    event?: ImpulseEvent;
} {
    return {
        flows: value.flows,
        priceHistory: value.priceHistory,
        liquidations: value.liquidations,
        event: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.event))
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
